<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE theme [
  <!ELEMENT theme (name,dtdversion,template+,stylesheet+,assoc+,reference*,mmtemplate*)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT dtdversion (#PCDATA)>
  <!ELEMENT template (tname,tencoding,tdata)>
  <!ELEMENT tname (#PCDATA)>
  <!ELEMENT tencoding (#PCDATA)>
  <!ELEMENT tdata (#PCDATA)>
  <!ELEMENT stylesheet (cssname,cssmediatype,cssencoding,cssdata)>
  <!ELEMENT cssname (#PCDATA)>
  <!ELEMENT cssmediatype (#PCDATA)>
  <!ELEMENT cssdata (#PCDATA)>
  <!ELEMENT assoc (assoc_tname,assoc_cssname)>
  <!ELEMENT assoc_tname (#PCDATA)>
  <!ELEMENT assoc_cssname (#PCDATA)>
  <!ELEMENT reference (refname,refencoded,reflocation,refdata)>
  <!ELEMENT refname (#PCDATA)>
  <!ELEMENT refencoded (#PCDATA)>
  <!ELEMENT reflocation (#PCDATA)>
  <!ELEMENT refdata (#PCDATA)>
  <!ELEMENT mmtemplate (mmtemplate_name,mmtemplate_data)>
  <!ELEMENT mmtemplate_name (#PCDATA)>
  <!ELEMENT mmtemplate_data (#PCDATA)>
]><theme>
  <name>culinary</name>
  <dtdversion>1.2</dtdversion>
  <template>
    <tname>culinary</tname>
    <tencoding></tencoding>
    <tdata><![CDATA[e3Byb2Nlc3NfcGFnZWRhdGF9DQo8IURPQ1RZUEUgaHRtbCBQVUJMSUMgIi0vL1czQy8vRFREIFhIVE1MIDEuMCBTdHJpY3QvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvVFIveGh0bWwxL0RURC94aHRtbDEtc3RyaWN0LmR0ZCI+DQo8aHRtbCB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94aHRtbCI+DQo8aGVhZD4NCjx0aXRsZT57c2l0ZW5hbWV9IC0ge3RpdGxlfTwvdGl0bGU+DQp7bWV0YWRhdGF9DQp7Y21zX3N0eWxlc2hlZXR9DQo8L2hlYWQ+DQo8Ym9keT4NCjxkaXYgaWQ9IndyYXBwZXIiPg0KICA8ZGl2IGlkPSJoZWFkZXIiPg0KICAgIDxkaXYgaWQ9ImxvZ28iPg0KICAgICAgPGgxPntzaXRlbmFtZX08L2gxPg0KICAgICAgPGgyPnlvdXIgc2xvZ2FuIGhlcmU8L2gyPg0KICAgIDwvZGl2Pg0KICAgIDwhLS0gZW5kIGRpdiNsb2dvIC0tPg0KICA8L2Rpdj4NCiAgPCEtLSBlbmQgZGl2I2hlYWRlciAtLT4NCiAgPGRpdiBpZD0ibWVudSI+DQogICAge21lbnUgdGVtcGxhdGU9ImN1bGluYXJ5IDogbWluaW1hbF9tZW51IiBudW1iZXJfb2ZfbGV2ZWxzPSIxIn0NCiAgPC9kaXY+DQogIDwhLS0gZW5kIGRpdiNtZW51IC0tPg0KICA8ZGl2IGlkPSJwYWdlIj4NCiAgICA8ZGl2IGlkPSJwYWdlLWJndG9wIj4NCiAgICAgIDxkaXYgaWQ9ImNvbnRlbnQiPg0KICAgICAgICA8ZGl2IGNsYXNzPSJwb3N0Ij4NCiAgICAgICAgICA8aDIgY2xhc3M9InRpdGxlIj57dGl0bGV9PC9oMj4NCg0KICAgICAgICAgIDxkaXYgY2xhc3M9ImVudHJ5Ij4NCiAgICAgICAgICAgIHtjb250ZW50fQ0KICAgICAgICAgIDwvZGl2Pg0KICAgICAgICAgIDxkaXYgY2xhc3M9Im1ldGEiPg0KICAgICAgICAgICAgPHAgY2xhc3M9ImxpbmtzIj57ZWRpdH0gfCB7cHJpbnR9PC9wPg0KICAgICAgICAgIDwvZGl2Pg0KICAgICAgICA8L2Rpdj4NCiAgICAgIDwvZGl2Pg0KICAgICAgPCEtLSBlbmQgZGl2I2NvbnRlbnQgLS0+DQogICAgICA8ZGl2IGlkPSJzaWRlYmFyIj4NCiAgICAgICAgPHVsPg0KICAgICAgICAgIDxsaT4NCiAgICAgICAgICAgIDxoMj5OYXZpZ2F0aW9uPC9oMj4NCiAgICAgICAgICAgIHttZW51IHRlbXBsYXRlPSJjdWxpbmFyeSA6IG1pbmltYWxfbWVudSIgc3RhcnRfbGV2ZWw9IjEiIGNvbGxhcHNlPSIxIn0NCiAgICAgICAgICA8L2xpPg0KICAgICAgICAgIDxsaT4NCiAgICAgICAgICAgIDxoMj5CZWJpbmR1bSBNYXVyaXM8L2gyPg0KICAgICAgICAgICAgPHVsPg0KICAgICAgICAgICAgICA8bGk+PGEgaHJlZj0iIyI+TmVjIG1ldHVzIHNlZCBkb25lYzwvYT48L2xpPg0KICAgICAgICAgICAgICA8bGk+PGEgaHJlZj0iIyI+TWFnbmEgbGFjdXMgYmliZW5kdW0gbWF1cmlzPC9hPjwvbGk+DQogICAgICAgICAgICAgIDxsaT48YSBocmVmPSIjIj5WZWxpdCBzZW1wZXIgbmlzaSBtb2xlc3RpZTwvYT48L2xpPg0KICAgICAgICAgICAgICA8bGk+PGEgaHJlZj0iIyI+RWdldCB0ZW1wb3IgZWdldCBub251bW15PC9hPjwvbGk+DQogICAgICAgICAgICAgIDxsaT48YSBocmVmPSIjIj5OZWMgbWV0dXMgc2VkIGRvbmVjPC9hPjwvbGk+DQogICAgICAgICAgICAgIDxsaT48YSBocmVmPSIjIj5WZWxpdCBzZW1wZXIgbmlzaSBtb2xlc3RpZTwvYT48L2xpPg0KICAgICAgICAgICAgICA8bGk+PGEgaHJlZj0iIyI+RWdldCB0ZW1wb3IgZWdldCBub251bW15PC9hPjwvbGk+DQogICAgICAgICAgICAgIDxsaT48YSBocmVmPSIjIj5WZWxpdCBzZW1wZXIgbmlzaSBtb2xlc3RpZTwvYT48L2xpPg0KICAgICAgICAgICAgPC91bD4NCiAgICAgICAgICA8L2xpPg0KICAgICAgICA8L3VsPg0KICAgICAgPC9kaXY+DQogICAgICA8IS0tIGVuZCBkaXYjc2lkZWJhciAtLT4NCiAgICAgIDxkaXYgc3R5bGU9ImNsZWFyOiBib3RoOyBoZWlnaHQ6IDFweCI+PC9kaXY+DQogICAgPC9kaXY+DQogIDwvZGl2Pg0KICA8IS0tIGVuZCBkaXYjcGFnZSAtLT4NCg0KPCEtLSANClRoaXMgdGhlbWUgaXMgcmVsZWFzZWQgZnJlZSBmb3IgdXNlIHVuZGVyIGNyZWF0aXZlIGNvbW1vbnMgbGljZW5jZS4gDQpBbGwgbGlua3MgaW4gdGhlIGZvb3RlciBzaG91bGQgcmVtYWluIGludGFjdC4gDQpUaGVzZSBsaW5rcyBhcmUgYWxsIGZhbWlseSBmcmllbmRseSBhbmQgd2lsbCBub3QgaHVydCB5b3VyIHNpdGUgaW4gYW55IHdheS4gDQotLT4NCg0KICA8ZGl2IGlkPSJmb290ZXIiPg0KICAgIDxwPkNvcHlyaWdodCAmY29weTsgMjAxMCB7c2l0ZW5hbWV9LiBBbGwgUmlnaHRzIFJlc2VydmVkLiBEZXNpZ24gYnkgPGEgaHJlZj0iaHR0cDovL3d3dy5mcmVlY3NzdGVtcGxhdGVzLm9yZy8iPkZyZWUgQ1NTIFRlbXBsYXRlczwvYT4uPC9wPg0KICA8L2Rpdj4NCiAgPCEtLSBlbmQgZGl2I2Zvb3RlciAtLT4NCjwvZGl2Pg0KPCEtLSBlbmQgZGl2I3dyYXBwZXIgLS0+DQo8L2JvZHk+DQo8L2h0bWw+]]></tdata>
  </template>
  <mmtemplate>
    <mmtemplate_name>minimal_menu</mmtemplate_name>
    <mmtemplate_data>eyogQ1NTIGNsYXNzZXMgdXNlZCBpbiB0aGlzIHRlbXBsYXRlOg0KLmN1cnJlbnRwYWdlIC0gVGhlIGFjdGl2ZS9jdXJyZW50IHBhZ2UNCi5idWxsZXRfc2VjdGlvbmhlYWRlciAtIFRvIHN0eWxlIHNlY3Rpb24gaGVhZGVyDQpoci5zZXBhcmF0b3IgLSBUbyBzdHlsZSB0aGUgcnVsZXIgZm9yIHRoZSBzZXBhcmF0b3IgKn0gDQp7aWYgJGNvdW50ID4gMH0NCjx1bCBjbGFzcz0iY2xlYXJmaXgiPg0Ke2ZvcmVhY2ggZnJvbT0kbm9kZWxpc3QgaXRlbT1ub2RlfQ0Ke2lmICRub2RlLT5kZXB0aCA+ICRub2RlLT5wcmV2ZGVwdGh9DQp7cmVwZWF0IHN0cmluZz0iPHVsPiIgdGltZXM9JG5vZGUtPmRlcHRoLSRub2RlLT5wcmV2ZGVwdGh9DQp7ZWxzZWlmICRub2RlLT5kZXB0aCA8ICRub2RlLT5wcmV2ZGVwdGh9DQp7cmVwZWF0IHN0cmluZz0iPC9saT48L3VsPiIgdGltZXM9JG5vZGUtPnByZXZkZXB0aC0kbm9kZS0+ZGVwdGh9DQo8L2xpPg0Ke2Vsc2VpZiAkbm9kZS0+aW5kZXggPiAwfTwvbGk+DQp7L2lmfQ0KDQp7aWYgJG5vZGUtPmN1cnJlbnQgPT0gdHJ1ZX0NCjxsaT48YSBocmVmPSJ7JG5vZGUtPnVybH0iIGNsYXNzPSJjdXJyZW50cGFnZSJ7aWYgJG5vZGUtPnRhcmdldCBuZSAiIn0gdGFyZ2V0PSJ7JG5vZGUtPnRhcmdldH0iey9pZn0+IHskbm9kZS0+bWVudXRleHR9IDwvYT4NCg0Ke2Vsc2VpZiAkbm9kZS0+cGFyZW50ID09IHRydWUgJiYgJG5vZGUtPmRlcHRoID09IDEgYW5kICRub2RlLT50eXBlICE9ICdzZWN0aW9uaGVhZGVyJyBhbmQgJG5vZGUtPnR5cGUgIT0gJ3NlcGFyYXRvcid9DQo8bGkgY2xhc3M9ImFjdGl2ZXBhcmVudCI+IDxhIGhyZWY9Inskbm9kZS0+dXJsfSIgY2xhc3M9ImFjdGl2ZXBhcmVudCJ7aWYgJG5vZGUtPnRhcmdldCBuZSAiIn0gdGFyZ2V0PSJ7JG5vZGUtPnRhcmdldH0iey9pZn0+IHskbm9kZS0+bWVudXRleHR9IDwvYT4NCg0Ke2Vsc2VpZiAkbm9kZS0+dHlwZSA9PSAnc2VjdGlvbmhlYWRlcid9DQo8bGkgY2xhc3M9InNlY3Rpb25oZWFkZXIiPnskbm9kZS0+bWVudXRleHR9DQoNCntlbHNlaWYgJG5vZGUtPnR5cGUgPT0gJ3NlcGFyYXRvcid9DQo8bGkgc3R5bGU9Imxpc3Qtc3R5bGUtdHlwZTogbm9uZTsiPiA8aHIgY2xhc3M9InNlcGFyYXRvciIgLz4NCg0Ke2Vsc2V9DQo8bGk+PGEgaHJlZj0ieyRub2RlLT51cmx9IntpZiAkbm9kZS0+dGFyZ2V0IG5lICIifSB0YXJnZXQ9Inskbm9kZS0+dGFyZ2V0fSJ7L2lmfT4geyRub2RlLT5tZW51dGV4dH0gPC9hPg0KDQp7L2lmfQ0KDQp7L2ZvcmVhY2h9DQoNCntyZXBlYXQgc3RyaW5nPSI8L2xpPjwvdWw+IiB0aW1lcz0kbm9kZS0+ZGVwdGgtMX08L2xpPg0KPC91bD4NCnsvaWZ9DQo=</mmtemplate_data>
  </mmtemplate>
  <stylesheet>
    <cssname>culinary</cssname>
    <cssmediatype></cssmediatype>
    <cssdata><![CDATA[KiB7DQoJbWFyZ2luOiAwOw0KCXBhZGRpbmc6IDA7DQp9DQoNCmJvZHkgew0KCW1hcmdpbjogMHB4Ow0KCWJhY2tncm91bmQ6ICNDMEMwQzA7DQoJdGV4dC1hbGlnbjoganVzdGlmeTsNCglmb250LWZhbWlseTogR2VvcmdpYSwgIlRpbWVzIE5ldyBSb21hbiIsIFRpbWVzLCBzZXJpZjsNCglmb250LXNpemU6IDEzcHg7DQoJZm9udC1zdHlsZTogaXRhbGljOw0KCWNvbG9yOiAjN0Q4MDdBOw0KfQ0KDQpoMSwgaDIsIGgzIHsNCgljb2xvcjogI0FBMjgwODsNCn0NCg0KaDEgew0KfQ0KDQpoMiB7DQp9DQoNCmgzIHsNCn0NCg0KcCwgYmxvY2txdW90ZSwgdWwsIG9sIHsNCgltYXJnaW4tYm90dG9tOiAyMHB4Ow0KCWxpbmUtaGVpZ2h0OiAyZW07DQp9DQoNCnAgew0KfQ0KDQpibG9ja3F1b3RlIHsNCn0NCg0KdWwsIG9sLCBsaSB7DQoJbWFyZ2luOiAwcHg7DQoJcGFkZGluZzogMHB4Ow0KCWxpc3Qtc3R5bGU6IG5vbmU7DQp9DQoNCmEgew0KCXRleHQtZGVjb3JhdGlvbjogdW5kZXJsaW5lOw0KCWNvbG9yOiAjRTE0OTQ5Ow0KfQ0KDQphOmhvdmVyIHsNCgl0ZXh0LWRlY29yYXRpb246IG5vbmU7DQoJY29sb3I6ICNDMTE0MTQ7DQp9DQoNCi8qIFdyYXBwZXIgKi8NCg0KI3dyYXBwZXIgew0KfQ0KDQovKiBIZWFkZXIgKi8NCg0KI2hlYWRlciB7DQoJd2lkdGg6IDkwMHB4Ow0KCWhlaWdodDogMTQwcHg7DQoJbWFyZ2luOiAwIGF1dG87DQoJYmFja2dyb3VuZDogdXJsKC9jbXNtcy91cGxvYWRzL2N1bGluYXJ5L2ltZzAxLmpwZykgbm8tcmVwZWF0IGxlZnQgdG9wOw0KfQ0KDQovKiBMb2dvICovDQoNCiNsb2dvIHsNCglmbG9hdDogbGVmdDsNCgl3aWR0aDogMjcwcHg7DQoJaGVpZ2h0OiA3MHB4Ow0KCW1hcmdpbjogMHB4Ow0KCXBhZGRpbmctbGVmdDogMzBweDsNCgl0ZXh0LWFsaWduOiBjZW50ZXI7DQp9DQoNCiNsb2dvIGgxIHsNCgltYXJnaW46IDA7DQoJcGFkZGluZzogMTBweCAwcHggMHB4IDBweDsNCgl0ZXh0LXRyYW5zZm9ybTogbG93ZXJjYXNlOw0KCWZvbnQ6IG5vcm1hbCA0NnB4IEdlb3JnaWEsICJUaW1lcyBOZXcgUm9tYW4iLCBUaW1lcywgc2VyaWY7DQp9DQoNCiNsb2dvIGgyIHsNCgltYXJnaW46IC0ycHggMCAwIDA7DQoJcGFkZGluZzogMDsNCgl0ZXh0LXRyYW5zZm9ybTogbG93ZXJjYXNlOw0KCWxldHRlci1zcGFjaW5nOiAycHg7DQoJZm9udC1zaXplOiAxMnB4Ow0KCWZvbnQtd2VpZ2h0OiBub3JtYWw7DQoJZm9udC1zdHlsZTogaXRhbGljOw0KCWNvbG9yOiAjRkZGRkZGOw0KfQ0KDQojbG9nbyBhIHsNCgl0ZXh0LWRlY29yYXRpb246IG5vbmU7DQoJY29sb3I6ICNGRkZGRkY7DQp9DQoNCi8qIE1lbnUgKi8NCg0KI21lbnUgew0KCXdpZHRoOiA4NzJweDsNCgloZWlnaHQ6IDQxcHg7DQoJbWFyZ2luOiAwIGF1dG87DQoJcGFkZGluZzogMHB4IDBweCAwcHggMjhweDsNCgliYWNrZ3JvdW5kOiB1cmwoL2Ntc21zL3VwbG9hZHMvY3VsaW5hcnkvaW1nMDIuanBnKSBuby1yZXBlYXQgbGVmdCB0b3A7DQp9DQoNCiNtZW51IHVsIHsNCgltYXJnaW46IDA7DQoJbGlzdC1zdHlsZTogbm9uZTsNCglsaW5lLWhlaWdodDogbm9ybWFsOw0KfQ0KDQojbWVudSBsaSB7DQoJZGlzcGxheTogaW5saW5lOw0KCXRleHQtYWxpZ246IGNlbnRlcjsNCn0NCg0KI21lbnUgYSB7DQoJaGVpZ2h0OiAzM3B4Ow0KCWRpc3BsYXk6IGJsb2NrOw0KCWZsb2F0OiBsZWZ0Ow0KCXBhZGRpbmc6IDhweCAyMHB4IDBweCAyMHB4Ow0KCXRleHQtZGVjb3JhdGlvbjogbm9uZTsNCgl0ZXh0LWFsaWduOiBjZW50ZXI7DQoJdGV4dC10cmFuc2Zvcm06IGxvd2VyY2FzZTsNCglmb250LWZhbWlseTogR2VvcmdpYSwgIlRpbWVzIE5ldyBSb21hbiIsIFRpbWVzLCBzZXJpZjsNCglmb250LXNpemU6IDE0cHg7DQoJZm9udC13ZWlnaHQ6IG5vcm1hbDsNCglmb250LXN0eWxlOiBpdGFsaWM7DQoJY29sb3I6ICNGRkZGRkY7DQp9DQoNCiNtZW51IGE6aG92ZXIsICNtZW51IC5hY3RpdmUgYSB7DQoJYmFja2dyb3VuZDogI0MxMTIxMjsNCgljb2xvcjogI0ZGRkZGRjsNCn0NCg0KI3NwbGFzaCB7DQoJd2lkdGg6IDk0MHB4Ow0KCWhlaWdodDogMjk5cHg7DQoJbWFyZ2luOiAwIGF1dG87DQp9DQoNCi8qIFNlYXJjaCAqLw0KDQojaGVhZGVyLXNlYXJjaCB7DQoJd2lkdGg6IDk0MHB4Ow0KCWhlaWdodDogNTFweDsNCgltYXJnaW46IDAgYXV0bzsNCglwYWRkaW5nOiAwcHggMHB4IDBweCAwcHg7DQp9DQoNCiNoZWFkZXItc2VhcmNoIGZvcm0gew0KCWZsb2F0OiByaWdodDsNCgl3aWR0aDogMzAwcHg7DQoJbWFyZ2luOiAwOw0KCXBhZGRpbmc6IDEycHggMHB4IDBweCAwcHg7DQp9DQoNCiNoZWFkZXItc2VhcmNoIGZpZWxkc2V0IHsNCgltYXJnaW46IDA7DQoJcGFkZGluZzogMDsNCglib3JkZXI6IG5vbmU7DQp9DQoNCiNoZWFkZXItc2VhcmNoLXRleHQgew0KCXdpZHRoOiAyMDBweDsNCglwYWRkaW5nOiAycHggM3B4Ow0KCWJhY2tncm91bmQ6ICMxRTFFMUU7DQoJYm9yZGVyOiBub25lOw0KCWNvbG9yOiAjNEQ0RDREOw0KfQ0KDQojaGVhZGVyLXNlYXJjaC1zdWJtaXQgew0KCWJhY2tncm91bmQ6IG5vbmU7DQoJYm9yZGVyOiBub25lOw0KCWZvbnQtZmFtaWx5OiBBcmlhbCwgSGVsdmV0aWNhLCBzYW5zLXNlcmlmOw0KCWZvbnQtc2l6ZTogMTJweDsNCgljb2xvcjogI0U0RTRFNDsNCn0NCg0KI3NlYXJjaCB7DQoJaGVpZ2h0OiA1MXB4Ow0KCW1hcmdpbjogMCBhdXRvOw0KCXBhZGRpbmc6IDBweCAwcHggNjBweCAwcHg7DQp9DQoNCiNzZWFyY2ggZm9ybSB7DQoJbWFyZ2luOiAwOw0KCXBhZGRpbmc6IDEycHggMHB4IDAgMDsNCn0NCg0KI3NlYXJjaCBmaWVsZHNldCB7DQoJbWFyZ2luOiAwOw0KCXBhZGRpbmc6IDA7DQoJYm9yZGVyOiBub25lOw0KfQ0KDQojc2VhcmNoIGlucHV0IHsNCglmbG9hdDogbGVmdDsNCglmb250OiAxMnB4IEFyaWFsLCBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7DQp9DQoNCiNzZWFyY2gtdGV4dCB7DQoJd2lkdGg6IDE2MHB4Ow0KCWhlaWdodDogMThweDsNCglwYWRkaW5nOiAzcHggMCAzcHggNXB4Ow0KCWJvcmRlcjogMXB4IHNvbGlkICM5OTk5OTk7DQoJY29sb3I6ICMwMDAwMDA7DQp9DQoNCiNzZWFyY2gtc3VibWl0IHsNCgltYXJnaW4tbGVmdDogMTBweDsNCglwYWRkaW5nOiA0cHggNHB4Ow0KCWJvcmRlcjogbm9uZTsNCgliYWNrZ3JvdW5kOiAjQzExMjEyOw0KCWZvbnQtc2l6ZTogMTBweDsNCgljb2xvcjogI0ZGRkZGRjsNCn0NCg0KLyogUGFnZSAqLw0KDQojcGFnZSB7DQoJd2lkdGg6IDg0NHB4Ow0KCW1hcmdpbjogMCBhdXRvOw0KCXBhZGRpbmc6IDBweCAyOHB4Ow0KCWJhY2tncm91bmQ6ICNGRkZGRkYgdXJsKC9jbXNtcy91cGxvYWRzL2N1bGluYXJ5L2ltZzA1LmpwZykgcmVwZWF0LXkgbGVmdCB0b3A7DQp9DQoNCi8qIENvbnRlbnQgKi8NCg0KI2NvbnRlbnQgew0KCWZsb2F0OiBsZWZ0Ow0KCXdpZHRoOiA1NjBweDsNCglwYWRkaW5nLXRvcDogMzBweDsNCn0NCi5wb3N0IHsNCgliYWNrZ3JvdW5kOiB1cmwoL2Ntc21zL3VwbG9hZHMvY3VsaW5hcnkvaW1nMDQuZ2lmKSByZXBlYXQteCBsZWZ0IGJvdHRvbTsNCgltYXJnaW46IDBweCAwcHggMzBweCAwcHg7DQp9DQoNCi5wb3N0IC50aXRsZSB7DQoJYmFja2dyb3VuZDogdXJsKC9jbXNtcy91cGxvYWRzL2N1bGluYXJ5L2ltZzAzLmpwZykgbm8tcmVwZWF0IGxlZnQgMHB4Ow0KCW1hcmdpbjogMHB4Ow0KCXBhZGRpbmc6IDBweCAwcHggMHB4IDQwcHg7DQoJbGV0dGVyLXNwYWNpbmc6IC0xcHg7DQoJdGV4dC1kZWNvcmF0aW9uOiBub25lOw0KCWZvbnQtZmFtaWx5OiBHZW9yZ2lhLCAiVGltZXMgTmV3IFJvbWFuIiwgVGltZXMsIHNlcmlmOw0KCWZvbnQtc2l6ZTogMjhweDsNCglmb250LXdlaWdodDogbm9ybWFsOw0KCWZvbnQtc3R5bGU6IGl0YWxpYzsNCgljb2xvcjogI0JGMEIwQjsNCn0NCg0KLnBvc3QgLmVudHJ5IHsNCglwYWRkaW5nOiAyMHB4IDBweDsNCn0NCg0KLnBvc3QgaW1nIHsNCglmbG9hdDogbGVmdDsNCglwYWRkaW5nOiAxNXB4IDBweDsNCn0NCg0KLnBvc3QgLm1ldGEgew0KCXRleHQtYWxpZ246IHJpZ2h0Ow0KCXBhZGRpbmc6IDBweCAwIDIwcHggMDsNCglmb250LXdlaWdodDogYm9sZDsNCgljb2xvcjogIzIwMjAyMDsNCn0NCg0KLnBvc3QgLmJ5bGluZSB7DQoJcGFkZGluZy1sZWZ0OiA0MHB4Ow0KCWZvbnQtc2l6ZTogMTJweDsNCglmb250LXN0eWxlOiBpdGFsaWM7DQoJdGV4dC10cmFuc2Zvcm06IGxvd2VyY2FzZTsNCgljb2xvcjogIzdEODA3QTsNCn0NCg0KLyogU2lkZWJhciAqLw0KDQojc2lkZWJhciB7DQoJZmxvYXQ6IHJpZ2h0Ow0KCXdpZHRoOiAyMzBweDsNCgltYXJnaW46IDIwcHggMHB4Ow0KCXBhZGRpbmc6IDEwcHggMHB4IDMwcHggMzBweDsNCn0NCg0KI3NpZGViYXIgdWwgew0KCW1hcmdpbjogMDsNCglwYWRkaW5nOiAwOw0KCWxpc3Qtc3R5bGU6IG5vbmU7DQoJbGluZS1oZWlnaHQ6IG5vcm1hbDsNCn0NCg0KI3NpZGViYXIgbGkgew0KCW1hcmdpbi1ib3R0b206IDFweDsNCn0NCg0KI3NpZGViYXIgbGkgdWwgew0KCW1hcmdpbjogMHB4Ow0KCXBhZGRpbmc6IDBweCAwcHggNDBweCAyN3B4Ow0KfQ0KDQojc2lkZWJhciBsaSBsaSB7DQoJbWFyZ2luOiAwOw0KCXBhZGRpbmc6IDlweCAwcHg7DQoJYm9yZGVyOiBub25lOw0KCWJhY2tncm91bmQ6IG5vbmU7DQp9DQoNCiNzaWRlYmFyIGgyIHsNCgltYXJnaW46IDBweDsNCglwYWRkaW5nOiAwcHggMHB4IDEwcHggMHB4Ow0KCWZvbnQtZmFtaWx5OiBHZW9yZ2lhLCAiVGltZXMgTmV3IFJvbWFuIiwgVGltZXMsIHNlcmlmOw0KCWZvbnQtc2l6ZTogMThweDsNCglmb250LXdlaWdodDogbm9ybWFsOw0KCWZvbnQtc3R5bGU6IGl0YWxpYzsNCgljb2xvcjogI0JGMEIwQjsNCn0NCg0KI3NpZGViYXIgaDMgew0KCWZvbnQtc2l6ZTogNzclOw0KCWNvbG9yOiAjMTEwNDA0Ow0KfQ0KDQojc2lkZWJhciBwIHsNCgltYXJnaW46IDA7DQoJbGluZS1oZWlnaHQ6IG5vcm1hbDsNCgljb2xvcjogI0Q0Qzc5MjsNCn0NCg0KI3NpZGViYXIgYSB7DQoJYm9yZGVyOiBub25lOw0KCXRleHQtZGVjb3JhdGlvbjogbm9uZTsNCgljb2xvcjogIzdEODA3QTsNCn0NCg0KI3NpZGViYXIgYTpob3ZlciB7DQoJdGV4dC1kZWNvcmF0aW9uOiB1bmRlcmxpbmU7DQp9DQoNCi8qIFN1Ym1lbnUgKi8NCg0KI3N1Ym1lbnUgew0KfQ0KDQovKiBOZXdzICovDQoNCiNuZXdzIHsNCn0NCg0KI25ld3MgYSB7DQoJZm9udC1zaXplOiA4NSU7DQp9DQoNCi8qIEZvb3RlciAqLw0KDQojZm9vdGVyIHsNCgl3aWR0aDogOTYwcHg7DQoJaGVpZ2h0OiAxMDBweDsNCgltYXJnaW46IDAgYXV0bzsNCglwYWRkaW5nOiAxNHB4IDBweCAwcHggMHB4Ow0KCWJhY2tncm91bmQ6IHVybChbW3Jvb3RfdXJsXV0vdXBsb2Fkcy9jdWxpbmFyeS9pbWcwNC5qcGcpIG5vLXJlcGVhdCBsZWZ0IHRvcDsNCgljb2xvcjogIzlDOUM5QzsNCn0NCg0KI2Zvb3RlciBwIHsNCgltYXJnaW46IDA7DQoJdGV4dC1hbGlnbjogY2VudGVyOw0KCWZvbnQtc2l6ZTogMTFweDsNCn0NCg0KI2Zvb3RlciBhIHsNCgl0ZXh0LWRlY29yYXRpb246IHVuZGVybGluZTsNCgljb2xvcjogIzgwODA4MDsNCn0NCg0KI2Zvb3RlciBhOmhvdmVyIHsNCgl0ZXh0LWRlY29yYXRpb246IG5vbmU7DQp9]]></cssdata>
  </stylesheet>
  <assoc>
    <assoc_tname>culinary : culinary</assoc_tname>
    <assoc_cssname>culinary : culinary</assoc_cssname>
  </assoc>
</theme>
